using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KnowledgeBase.Migrations
{
    public partial class PopulateAllOthersFrameworks : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (02, 'NC02', '.NET Core', '1.1')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (03, 'NC03', '.NET Core', '1.2')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (04, 'NC04', '.NET Core', '1.2')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (05, 'NC05', '.NET Core', '1.3')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (06, 'NC06', '.NET Core', '1.4')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (07, 'NC07', '.NET Core', '1.5')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (08, 'NC08', '.NET Core', '1.6')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (09, 'NC09', '.NET Core', '1.7')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (10, 'NC10', '.NET Core', '1.8')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (11, 'NC11', '.NET Core', '1.9')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (12, 'NC12', '.NET Core', '1.10')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (13, 'NC13', '.NET Core', '1.11')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (15, 'NC15', '.NET Core', '1.12')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (15, 'NC15', '.NET Core', '1.13')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (16, 'NC16', '.NET Core', '1.14')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (17, 'NC17', '.NET Core', '1.15')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (18, 'NC18', '.NET Core', '1.16')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (19, 'NC19', '.NET Core', '1.17')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (20, 'NC20', '.NET Core', '1.18')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (21, 'NC21', '.NET Core', '1.19')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (22, 'NC22', '.NET Core', '1.20')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (23, 'NC23', '.NET Core', '1.21')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (25, 'NC25', '.NET Core', '1.22')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (25, 'NC25', '.NET Core', '1.23')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (26, 'NC26', '.NET Core', '1.24')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (27, 'NC27', '.NET Core', '1.25')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (28, 'NC28', '.NET Core', '1.26')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (29, 'NC29', '.NET Core', '1.27')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (30, 'NC30', '.NET Core', '1.28')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (31, 'NC31', '.NET Core', '1.29')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (32, 'NC32', '.NET Core', '1.30')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (33, 'NC33', '.NET Core', '1.31')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (35, 'NC35', '.NET Core', '1.32')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (36, 'NC36', '.NET Core', '1.34')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (37, 'NC37', '.NET Core', '1.35')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (38, 'NC38', '.NET Core', '1.36')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (39, 'NC39', '.NET Core', '1.37')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (40, 'NC40', '.NET Core', '1.38')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (41, 'NC41', '.NET Core', '1.39')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (42, 'NC42', '.NET Core', '1.40')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (43, 'NC43', '.NET Core', '1.41')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (45, 'NC45', '.NET Core', '1.42')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (46, 'NC46', '.NET Core', '1.44')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (47, 'NC47', '.NET Core', '1.45')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (48, 'NC48', '.NET Core', '1.46')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (49, 'NC49', '.NET Core', '1.47')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (50, 'NC50', '.NET Core', '1.48')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (51, 'NC51', '.NET Core', '1.49')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (52, 'NC52', '.NET Core', '1.50')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (53, 'NC53', '.NET Core', '1.51')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (01, 'NC01', '.NET Framework', '1.0')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (02, 'NC02', '.NET Framework', '1.1')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (03, 'NC03', '.NET Framework', '1.2')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (04, 'NC04', '.NET Framework', '1.2.1')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (05, 'NC05', '.NET Framework', '1.3')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (06, 'NC06', '.NET Framework', '1.4')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (07, 'NC07', '.NET Framework', '1.5')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (08, 'NC08', '.NET Framework', '1.6')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (09, 'NC09', '.NET Framework', '1.7')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (10, 'NC10', '.NET Framework', '1.8')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (11, 'NC11', '.NET Framework', '1.9')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (12, 'NC12', '.NET Framework', '1.10')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (13, 'NC13', '.NET Framework', '1.11')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (15, 'NC15', '.NET Framework', '1.12')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (15, 'NC15', '.NET Framework', '1.13')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (16, 'NC16', '.NET Framework', '1.14')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (17, 'NC17', '.NET Framework', '1.15')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (18, 'NC18', '.NET Framework', '1.16')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (19, 'NC19', '.NET Framework', '1.17')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (20, 'NC20', '.NET Framework', '1.18')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (21, 'NC21', '.NET Framework', '1.19')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (22, 'NC22', '.NET Framework', '1.20')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (23, 'NC23', '.NET Framework', '1.21')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (24, 'NC24', '.NET Framework', '1.2')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (25, 'NC25', '.NET Framework', '1.23')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (26, 'NC26', '.NET Framework', '1.24')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (27, 'NC27', '.NET Framework', '1.25')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (28, 'NC28', '.NET Framework', '1.26')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (29, 'NC29', '.NET Framework', '1.27')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (30, 'NC30', '.NET Framework', '1.28')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (31, 'NC31', '.NET Framework', '1.29')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (32, 'NC32', '.NET Framework', '1.30')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (33, 'NC33', '.NET Framework', '1.31')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (34, 'NC34', '.NET Framework', '1.311')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (35, 'NC35', '.NET Framework', '1.32')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (36, 'NC36', '.NET Framework', '1.34')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (37, 'NC37', '.NET Framework', '1.35')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (38, 'NC38', '.NET Framework', '1.36')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (39, 'NC39', '.NET Framework', '1.37')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (40, 'NC40', '.NET Framework', '1.38')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (41, 'NC41', '.NET Framework', '1.39')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (42, 'NC42', '.NET Framework', '1.40')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (43, 'NC43', '.NET Framework', '1.41')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (44, 'NC44', '.NET Framework', '1.42')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (45, 'NC45', '.NET Framework', '1.43')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (46, 'NC46', '.NET Framework', '1.44')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (47, 'NC47', '.NET Framework', '1.45')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (48, 'NC48', '.NET Framework', '1.46')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (49, 'NC49', '.NET Framework', '1.47')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (50, 'NC50', '.NET Framework', '1.48')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (51, 'NC51', '.NET Framework', '1.49')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (52, 'NC52', '.NET Framework', '1.50')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (53, 'NC53', '.NET Framework', '1.51')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (18, 'JV18', 'Java', '1.16')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (19, 'JV19', 'Java', '1.17')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (20, 'JV20', 'Java', '1.18')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (21, 'JV21', 'Java', '1.19')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (22, 'JV22', 'Java', '1.20')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (23, 'JV23', 'Java', '1.21')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (25, 'JV25', 'Java', '1.22')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (25, 'JV25', 'Java', '1.23')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (26, 'JV26', 'Java', '1.24')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (27, 'JV27', 'Java', '1.25')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (28, 'JV28', 'Java', '1.26')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (29, 'JV29', 'Java', '1.27')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (30, 'JV30', 'Java', '1.28')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (31, 'JV31', 'Java', '1.29')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (32, 'JV32', 'Java', '1.30')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (33, 'JV33', 'Java', '1.31')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (34, 'JV34', 'Java', '1.32')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (35, 'JV35', 'Java', '1.33')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (36, 'JV36', 'Java', '1.34')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (37, 'JV37', 'Java', '1.35')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (38, 'JV38', 'Java', '1.36')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (39, 'JV39', 'Java', '1.37')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (40, 'JV40', 'Java', '1.38')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (41, 'JV41', 'Java', '1.39')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (42, 'JV42', 'Java', '1.40')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (43, 'JV43', 'Java', '1.41')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (45, 'JV45', 'Java', '1.42')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (46, 'JV46', 'Java', '1.44')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (47, 'JV47', 'Java', '1.45')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (48, 'JV48', 'Java', '1.46')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (49, 'JV49', 'Java', '1.47')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (50, 'JV50', 'Java', '1.48')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (51, 'JV51', 'Java', '1.49')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (52, 'JV52', 'Java', '1.50')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (53, 'JV53', 'Java', '1.51')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (01, 'P01', 'PHP', '1.0')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (02, 'P02', 'PHP', '1.1')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (03, 'P03', 'PHP', '1.2')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (04, 'P04', 'PHP', '1.3')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (05, 'P05', 'PHP', '1.4')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (06, 'P06', 'PHP', '1.5')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (07, 'P07', 'PHP', '1.6')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (08, 'P08', 'PHP', '1.7')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (09, 'P09', 'PHP', '1.8')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (10, 'P10', 'PHP', '1.9')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (11, 'P11', 'PHP', '1.10')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (12, 'P12', 'PHP', '1.11')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (13, 'P13', 'PHP', '1.12')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (15, 'P15', 'PHP', '1.13')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (16, 'P16', 'PHP', '1.14')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (17, 'P17', 'PHP', '1.16')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (18, 'P18', 'PHP', '1.17')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (19, 'P19', 'PHP', '1.18')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (20, 'P20', 'PHP', '1.19')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (21, 'P21', 'PHP', '1.20')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (22, 'P22', 'PHP', '1.21')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (23, 'P23', 'PHP', '1.22')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (25, 'P25', 'PHP', '1.24')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (26, 'P26', 'PHP', '1.25')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (27, 'P27', 'PHP', '1.26')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (28, 'P28', 'PHP', '1.27')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (29, 'P29', 'PHP', '1.28')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (30, 'P30', 'PHP', '1.29')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (31, 'P31', 'PHP', '1.30')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (32, 'P32', 'PHP', '1.31')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (33, 'P33', 'PHP', '1.32')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (35, 'P35', 'PHP', '1.33')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (35, 'P35', 'PHP', '1.34')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (36, 'P36', 'PHP', '1.35')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (37, 'P37', 'PHP', '1.36')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (38, 'P38', 'PHP', '1.37')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (39, 'P39', 'PHP', '1.38')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (40, 'P40', 'PHP', '1.39')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (41, 'P41', 'PHP', '1.40')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (42, 'P42', 'PHP', '1.41')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (43, 'P43', 'PHP', '1.42')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (44, 'P44', 'PHP', '1.43')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (45, 'P45', 'PHP', '1.44')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (46, 'P46', 'PHP', '1.45')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (47, 'P47', 'PHP', '1.46')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (48, 'P48', 'PHP', '1.47')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (49, 'P49', 'PHP', '1.48')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (50, 'P50', 'PHP', '1.49')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (51, 'P51', 'PHP', '1.50')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (52, 'P52', 'PHP', '1.51')");
            migrationBuilder.Sql("INSERT INTO Frameworks (Plataforma, Apelido, Descricao, Versao) VALUES (53, 'P53', 'PHP', '1.52')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 1");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 2");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 3");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 4");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 5");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 6");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 7");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 8");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 9");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 10");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 11");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 12");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 13");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 14");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 15");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 16");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 17");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 18");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 19");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 20");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 21");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 22");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 23");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 24");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 25");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 26");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 27");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 28");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 29");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 30");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 31");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 32");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 33");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 34");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 35");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 36");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 37");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 38");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 39");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 40");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 41");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 42");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 43");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 44");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 45");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 46");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 47");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 48");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 49");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 50");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 51");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 52");
            migrationBuilder.Sql("DELETE FROM Frameworks WHERE Plataforma = 53");
        }
    }
}
