using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KnowledgeBase.Migrations
{
    public partial class PopulateAutores : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('eepVohFwhpTnVjEPRSVQpltub_*TrJUzKJRZFiipH]', 93)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('d*McRLy*wXFfZsNknzIxSKSnGleK$sBWpO*w$y[KKd', 94)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('KanENOHdVedqXmmzuzEC[BpZWGsclO]GmzWi$GgTug', 95)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('wGtj$xYh_RhtqjqiOta]GpKDYBCW]@IpiBqH*y[[MS', 96)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('itOClPOiP[bGpLd@Vx[vOZiAaWUcSPiEmegNcKGodY', 97)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('g_RSs$LLMQNuXQtT$pPMd$TPqS@nOSBafWNljNsbRy', 98)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('o$BRCCqPOF$nNwC[CPwWvlyHzvkVXTC@XQAupvjQBG', 99)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('yzFYEoU$gzPmhmq*jRGdVWmPKqdXpW]cMFkWGzTFFk', 100)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('cPgxltHXf$vDvyuDozgpYwHp*kIGi$au]QUh_ZUhuj', 101)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('wgNJMZ@UIgu[gv@eMrjpDpI$hggFWR@SkG_iZDjKdc', 102)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('OspSgoBhzzoreC$ucQT[*Ghn]pP]USFsykuLP]cjOZ', 103)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('nCYTIoAagec[@QHGNzvpdHciuzNlmN_wLFzYkwfzfd', 104)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('GWFukw$*jSik@$]_Q$nZIxeAIVWm$o_iWFYcl@cbgH', 105)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('[Bm[V[ZrSpB*NqAXJrZG_pPGWk[NMjclQS$pXtGviG', 106)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('RNQwYLUvRMYvrBFP[cKdspCGyUnGao$[UIRHCiswAs', 107)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('RyjpffHEVbjT[PSYmWKLHSRuJDx_ecxSaIjaUuquXW', 108)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('fNhNIq$UdOWTepz@EAHSZeeBegd*TMLcpbnPo[RDLM', 109)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('bQCU$DCQfSo]*_kQlGA[doFEVzlDmNKLC@sdxpM@ZR', 110)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('toNLSpbSW$yqRgC@*UHKPLXRK*JvsYwQZppevIPRHW', 111)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('vRgionySVxehaTrhVfu]$lQZrivLCKs@Ncc@bRPNDT', 112)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('p]MGACCQGoiUAAzB_NqnIkmitBeEe$yAsvVDqA*isX', 113)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('*UBAHXRVmbLTKYTqku_YuYkurHfqzvmOvRqZgtivQF', 114)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('Fiy_LXCEKOgURbXNBqOCs_mFsdJp[F*dklRZMckygp', 115)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('NA$kSjAXBYZQoHBhGeXhAx@cZUXpwiAUTwNkdUYTkn', 116)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('GinbVo_ayXTZ]EFXFKxcfzSpDQteH$zTRPtFbUbBJq', 117)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('YorXBeqcpnobxcJMaEPTL@ejbep[DQAmzXnQOSRf@R', 118)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('yMDooYd@xUzCOBpFadwAxcwAgTpvYcGOtoyQ_IGcpK', 119)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('CQbuXJFsIppSNBDnpBkMO*TmknG@t[MUUx@Qm_AbuF', 120)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('wepqNeYBKZx$p@yz]XfVMefJIdipSeCEAHYSinRK_z', 121)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('cUUmDi$OPBQRfBCsIZGr$xLfutdxfOgg_SMeXRB*PG', 122)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('M$fXQAKem*[AOnptEW*_*EsF]mpfQpBvNjO@Rhswyn', 123)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('tvhhKETP*_Xpq]umRVpWhpciXOZSaiulGLUWBw[kgO', 124)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('G[MtOJaCErOniD@em[]Hyncyi[xxdknhQX$]wxs_dd', 125)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('VUGYpGxVYAXmTAuuJSmDKfU[L_SLWLKtR*FaXOQKJ@', 126)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('tovKKRfZm@nSxsT_sJAYHpBpKNZILludBU*_ZpQnkO', 127)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('nYRZw_JCMYpCZleWIs*yDyje@B@ubrrPqCojdjNBQN', 128)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('wXN[orVvAnZyKs*Pdn@lusbePlTMsI$IhweUEKtepE', 129)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('k*ra*LirGoJEkp_go_qwqhclpPBpTUqnSd[bUYHwv]', 130)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('d]geNJ_pcf[q@DEFLlMuwjGikbUmYIRmlDp*Bp$[EN', 131)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('OUJ_[_bTqGWmBUHNcPFj]_jiJTuCmpdOo$kcOmT_vG', 132)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('DCMaJNYhHxpi@IRpnnsWn[SFrN@dEysTKcj@FnBH]t', 133)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('USPO*FT[pLOIhlGuVrKjtwmxKo]AIYNkhTBhrCfXQt', 134)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('iBCbjHqmfLzvCpiLDM]nXiJqqVDHmfckppFfVznpl@', 135)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('tzHa@Xp[bTjqyLxt[vFgGklIQwcoyzSkKrfitOU_E_', 136)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('*SToPnQTK@iRPFXNIxjqhhXIhXyI[iS@brMUuLrOuD', 137)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('vnHbpuVJYwOvQT[HRVYRVZpTHurWpwgTnynNdeTmoh', 138)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('QNADxAEyThL]kxpL[gZWaM]TIoM_jiSg*xDXEU**nm', 139)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('jMTnQwwpAbiPr@u@wyx[_DWFiSUG[tzsn$YwSyNkhN', 140)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('biKmfkLCfO_dpbECsgCJDkpbTjR_@wYlksmTj*YaH]', 141)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('yPrMtvXqwTJTWgs]QbxFetjZ$JzaUSsLOx]ADv_b*y', 142)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('BKlpHNKcx_gUFBiQeRSQJydG$pLfrCKXzPqODasK[C', 143)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('CymQsKAsewHqAn_M_qGKetODWelXdmCZE$fquncDMK', 144)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('AiwOxhTaabk]IeyndTEMJu_hQDCVPgZupkipBvuVdp', 145)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('krBEExKWkOpv_idJebS*pzqAxaO_JHLslEBqVJVi$b', 146)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('ORM]q$pAhpNJmUWhtKbrsrlJuzDZ*RAoHTp[NX*zVi', 147)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('KFuCygYd[qkujnBYqGg_KVuUxjQY[YBZXvvEFBQitj', 148)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('$nMkovAhCUjGnBYxiMxfNwDLTLtEsabwMpG*SapoKS', 149)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('HEgfPDNtjsutnnlfsGepajevemFDpbXgfb_wipbKWr', 150)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('GnEuYeGtuFm$yxp]pwnOwtYVHAiU*zpcsKOGnyPPPx', 151)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('oRoDHMzinVLZ@wfBwcWSa]SdfTyZb$EhmAC_qGiy*F', 152)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('tpmOVOLlXCfZoyCsZ[nWMhOWbJPtCqVPLhNxY$BADk', 153)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('qtPWe*_dgTOpQwfNsqE*GpfXgFTXZEbJ*xhNtwZvHi', 154)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('VpQRKYahbEapBOlSz$Lvd*JRUmNcQipC]yB@JpMlFT', 155)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('wP_kqQXBGvqkpKlmYnpuGJlfkBcWXOnX@GEfq$EN[Q', 156)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('GX]zOoea$hlvWvLHAmebwZilVQOQydLrf_u_Zbgkxc', 157)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('iP[M]aBHgVtteHwMEtwFVVp@VMy[fSc*CzPLWuNOBG', 158)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('YZtiFVALrjWHqaxfqSzpANpqZqyHzikvRx_ppwGbs_', 159)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('mpOg_bxeFHZnnmecAXySoZSEVtvInhD$zxTopmzyhX', 160)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('mvwMqCBYpvirTKDKpLFB*_RMRvtiE]UvRdBpcADVWz', 161)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('VRPZwKELKTwQr*YWJySR*OWhpmkbXlySpyeiSrIhjg', 162)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('IpAVGjj[MiR_EUjSjN_nzTgeaNflM*IosEJStePNii', 163)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('w_D$UrcjzdQo_BK*UBt[jHJNUNsMTXchYeQAXmtis*', 164)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('PVZVGnasLcApmPma[nfHbVZY*dbtneRW@eavwPQOyV', 165)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('QnbdAqe$skHwLNyMISzTZMBgw$YhYrGBptAIGYCEbM', 166)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('bJ*YUR[nzqWoRGqaHUYCgrifZ$sVDWmkNlp*WmsDMf', 167)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('ow_NimkgAshmPchcCWP_mdhTYkL]ZKBZEeQNDfE_JZ', 168)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('AZtXvKbQnYDKJDwvkPf$tQSbmpsSZRPCpnVfryVUSc', 169)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('dkYnApVgjUYP*DRA@InibESSHw$HkYBealn[IQKkbd', 170)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES (']hrYH]flg_Y[mB]bzWBg_jOGFVikCtn$y]Kpu@K*MZ', 171)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('caDrkgh]hS*kdlNHzeNw*uenOFea[YkXF$J]JYuHru', 172)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('Q@EJDm]LpFKsIThWgWhRqncxF@ujLuNYZXNyHCPpF[', 173)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('LzPDaNH@drxpHp@ebcHSQAhOZSBT_XagTAXDVUIkDn', 174)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES (']DfmlMhnE_Pljge_dwN*jBGKTjZ*gzoWpsrPgf_aor', 175)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('EUcG]vwKCCajXeqTIYYajpVxo_fmNgWpVMbxdfuifj', 176)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('u]@VCaac*c*l_vKNni]TRggXAPt*zH@MTVL]R]rGj@', 177)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('KjAarjiWZkEJLYI*bxEUTxetIc$pp*TWMJcZZsvGpY', 178)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('ap[yIiZTtpMUMBRpZiWCTo*skyQaf@ItRNIR[sCx]I', 179)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('mDpoQZYzrixERWg*gED*LIIVcgyEglcQ_Vm[BYvOWf', 180)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('_fbIAqNvy*zOyjBFAaeeHqomgc]tu]VHBpltCfMmOj', 181)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('ab]fgdthQdpmIx$ssdJ$afmbyvtQVLkPT@KKCf$urC', 182)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('bdqHDnCfAfCFNsWKujTNfwoVFL$pPIm[JigfNMw@qq', 183)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('zeWbf_gCSoFHmAtZejlCKJAlJzIl_e*pYGhexAOpY_', 184)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('xPDwQ@[nABOaqXMesm_RkeKrMRDJbf]px_fWHplPCU', 185)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('Uex_rOmuxeffRoDKco@@kYkgKDLqJONek@_onPipsi', 186)");
            migrationBuilder.Sql("INSERT INTO Autores (Name, ArtigoId) VALUES ('vSOAQrklVXRQQ**ebiZCQgNrhfWubKjpPgReZdliMD', 187)");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 93)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 94)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 95)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 96)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 97)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 98)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 99)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 100)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 101)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 102)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 103)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 104)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 105)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 106)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 107)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 108)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 109)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 110)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 111)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 112)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 113)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 114)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 115)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 116)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 117)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 118)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 119)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 120)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 121)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 122)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 123)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 124)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 125)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 126)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 127)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 128)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 129)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 130)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 131)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 132)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 133)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 134)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 135)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 136)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 137)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 138)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 139)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 140)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 141)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 142)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 143)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 144)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 145)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 146)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 147)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 148)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 149)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 150)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 151)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 152)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 153)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 154)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 155)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 156)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 157)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 158)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 159)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 160)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 161)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 162)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 163)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 164)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 165)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 166)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 167)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 168)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 169)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 170)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 171)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 172)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 173)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 174)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 175)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 176)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 177)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 178)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 179)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 180)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 181)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 182)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 183)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 184)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 185)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 186)");
            migrationBuilder.Sql("DELETE FROM Autores WHERE ArtigoId = 187)");
        }
    }
}
