using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KnowledgeBase.Migrations
{
    public partial class PopulateArtigos : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Q__C]kEBP@_bVAyvgbxjwbNh[E6jKNiGNPiFdfrbZI', 'Q__C]kEBP@_bVAyvgbxjwbNh[E6jKNiGNPiFdfrbZIAhwJQLUUbMTdhVtlw@bEpabOslckJWLfLTEagbyHwLlR@JBBDFnuoiMbgvSD[Ir@]qSvG@lfw[aKVqVZYGHqtOPgvHg6hD@JJLEXJHAqYnSrahPvAIejMswDKuTaoz', 51)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('AhwJQLUUbMTdhVtlw@bEpabOslckJWLfLTEagbyHwL', 'AhwJQLUUbMTdhVtlw@bEpabOslckJWLfLTEagbyHwLlR@JBBDFnuoiMbgvSD[Ir@]qSvG@lfw[aKVqVZYGHqtOPgvHg6hD@JJLEXJHAqYnSrahPvAIejMswDKuTaoznTIPqadaNBFzltWnHMAFEuTlGKhf[rmIPxL_qmIDMg', 52)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('lR@JBBDFnuoiMbgvSD[Ir@]qSvG@lfw[aKVqVZYGHq', 'lR@JBBDFnuoiMbgvSD[Ir@]qSvG@lfw[aKVqVZYGHqtOPgvHg6hD@JJLEXJHAqYnSrahPvAIejMswDKuTaoznTIPqadaNBFzltWnHMAFEuTlGKhf[rmIPxL_qmIDMgbNxiXSembULaiQZZCTtRhj[q6qqrmSJvKRyDNQ[mfH', 53)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('tOPgvHg6hD@JJLEXJHAqYnSrahPvAIejMswDKuTaoz', 'tOPgvHg6hD@JJLEXJHAqYnSrahPvAIejMswDKuTaoznTIPqadaNBFzltWnHMAFEuTlGKhf[rmIPxL_qmIDMgbNxiXSembULaiQZZCTtRhj[q6qqrmSJvKRyDNQ[mfHCgrxPPmWMXRTqulUmzRf@NZjrtSb]DId[VFUzsS@g]', 54)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('nTIPqadaNBFzltWnHMAFEuTlGKhf[rmIPxL_qmIDMg', 'nTIPqadaNBFzltWnHMAFEuTlGKhf[rmIPxL_qmIDMgbNxiXSembULaiQZZCTtRhj[q6qqrmSJvKRyDNQ[mfHCgrxPPmWMXRTqulUmzRf@NZjrtSb]DId[VFUzsS@g]CIdXHafHIJrKDavoSh]DimzbadFNAey]Xvn]m`qFzj', 55)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('bNxiXSembULaiQZZCTtRhj[q6qqrmSJvKRyDNQ[mfH', 'bNxiXSembULaiQZZCTtRhj[q6qqrmSJvKRyDNQ[mfHCgrxPPmWMXRTqulUmzRf@NZjrtSb]DId[VFUzsS@g]CIdXHafHIJrKDavoSh]DimzbadFNAey]Xvn]m`qFzje6jxrLebkdfb_y_WLgGdwQgDk@Seuu[xYmandbb@an', 56)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('CgrxPPmWMXRTqulUmzRf@NZjrtSb]DId[VFUzsS@g]', 'CgrxPPmWMXRTqulUmzRf@NZjrtSb]DId[VFUzsS@g]CIdXHafHIJrKDavoSh]DimzbadFNAey]Xvn]m`qFzje6jxrLebkdfb_y_WLgGdwQgDk@Seuu[xYmandbb@anmGpLggTGrwbYOEJxgU]aDJk6bFnaQvNCuZcAkK_zgZ', 57)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('CIdXHafHIJrKDavoSh]DimzbadFNAey]Xvn]m`qFzj', 'CIdXHafHIJrKDavoSh]DimzbadFNAey]Xvn]m`qFzje6jxrLebkdfb_y_WLgGdwQgDk@Seuu[xYmandbb@anmGpLggTGrwbYOEJxgU]aDJk6bFnaQvNCuZcAkK_zgZEgZcPn[ZsNp@wucgzFCyeSFqUPPgNxWCySiarnzHgC', 58)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('e6jxrLebkdfb_y_WLgGdwQgDk@Seuu[xYmandbb@an', 'e6jxrLebkdfb_y_WLgGdwQgDk@Seuu[xYmandbb@anmGpLggTGrwbYOEJxgU]aDJk6bFnaQvNCuZcAkK_zgZEgZcPn[ZsNp@wucgzFCyeSFqUPPgNxWCySiarnzHgCbzRd6XvEHTnHjlSMsl[PomWSiUdyr6GCaAydkNubJr', 59)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('mGpLggTGrwbYOEJxgU]aDJk6bFnaQvNCuZcAkK_zgZ', 'mGpLggTGrwbYOEJxgU]aDJk6bFnaQvNCuZcAkK_zgZEgZcPn[ZsNp@wucgzFCyeSFqUPPgNxWCySiarnzHgCbzRd6XvEHTnHjlSMsl[PomWSiUdyr6GCaAydkNubJrkczJgr6eZMSRsUsGqgGyiTsPD]gIuJKAl@mbJedtff', 60)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('EgZcPn[ZsNp@wucgzFCyeSFqUPPgNxWCySiarnzHgC', 'EgZcPn[ZsNp@wucgzFCyeSFqUPPgNxWCySiarnzHgCbzRd6XvEHTnHjlSMsl[PomWSiUdyr6GCaAydkNubJrkczJgr6eZMSRsUsGqgGyiTsPD]gIuJKAl@mbJedtffbokivqORHR]ibgCoy]wwOUKHjhcGxpm@odbvkHWPDn', 61)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('bzRd6XvEHTnHjlSMsl[PomWSiUdyr6GCaAydkNubJr', 'bzRd6XvEHTnHjlSMsl[PomWSiUdyr6GCaAydkNubJrkczJgr6eZMSRsUsGqgGyiTsPD]gIuJKAl@mbJedtffbokivqORHR]ibgCoy]wwOUKHjhcGxpm@odbvkHWPDnb6Yqneimdg6_6OuBvERNYjYvGvZKbRUBzHwsWD_eKE', 62)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('kczJgr6eZMSRsUsGqgGyiTsPD]gIuJKAl@mbJedtff', 'kczJgr6eZMSRsUsGqgGyiTsPD]gIuJKAl@mbJedtffbokivqORHR]ibgCoy]wwOUKHjhcGxpm@odbvkHWPDnb6Yqneimdg6_6OuBvERNYjYvGvZKbRUBzHwsWD_eKEqAsFhoSfIyOQkEGKjBKeQvbbMiGUauaHCiZKKb]MR[', 63)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('bokivqORHR]ibgCoy]wwOUKHjhcGxpm@odbvkHWPDn', 'bokivqORHR]ibgCoy]wwOUKHjhcGxpm@odbvkHWPDnb6Yqneimdg6_6OuBvERNYjYvGvZKbRUBzHwsWD_eKEqAsFhoSfIyOQkEGKjBKeQvbbMiGUauaHCiZKKb]MR[NwaV6fiN@OOvK_BdPyznGb_@MwkZbXSnjlYVxXgFks', 64)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('b6Yqneimdg6_6OuBvERNYjYvGvZKbRUBzHwsWD_eKE', 'b6Yqneimdg6_6OuBvERNYjYvGvZKbRUBzHwsWD_eKEqAsFhoSfIyOQkEGKjBKeQvbbMiGUauaHCiZKKb]MR[NwaV6fiN@OOvK_BdPyznGb_@MwkZbXSnjlYVxXgFksGs]bFDKbja@H[JRIngkHWKIKkJcqkbPWaGhMEsuGdY', 65)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('qAsFhoSfIyOQkEGKjBKeQvbbMiGUauaHCiZKKb]MR[', 'qAsFhoSfIyOQkEGKjBKeQvbbMiGUauaHCiZKKb]MR[NwaV6fiN@OOvK_BdPyznGb_@MwkZbXSnjlYVxXgFksGs]bFDKbja@H[JRIngkHWKIKkJcqkbPWaGhMEsuGdYMffe[qqr_tr[gEyYJsMcHAccZDJkKDNvyJFaRQglQe', 66)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('NwaV6fiN@OOvK_BdPyznGb_@MwkZbXSnjlYVxXgFks', 'NwaV6fiN@OOvK_BdPyznGb_@MwkZbXSnjlYVxXgFksGs]bFDKbja@H[JRIngkHWKIKkJcqkbPWaGhMEsuGdYMffe[qqr_tr[gEyYJsMcHAccZDJkKDNvyJFaRQglQeCDjHlpSKNqRP@@sg]TT6sA]swmGsnwPbkmIpOI__aS', 67)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Gs]bFDKbja@H[JRIngkHWKIKkJcqkbPWaGhMEsuGdY', 'Gs]bFDKbja@H[JRIngkHWKIKkJcqkbPWaGhMEsuGdYMffe[qqr_tr[gEyYJsMcHAccZDJkKDNvyJFaRQglQeCDjHlpSKNqRP@@sg]TT6sA]swmGsnwPbkmIpOI__aSAsBEchHXzrQiFuCxbVqQVclCjTZtPzSgQW[xnhRILi', 68)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Mffe[qqr_tr[gEyYJsMcHAccZDJkKDNvyJFaRQglQe', 'Mffe[qqr_tr[gEyYJsMcHAccZDJkKDNvyJFaRQglQeCDjHlpSKNqRP@@sg]TT6sA]swmGsnwPbkmIpOI__aSAsBEchHXzrQiFuCxbVqQVclCjTZtPzSgQW[xnhRILiOR]NeYC@ErFCKCT_gx]ukU]d@@BIxa]rbZiBQikIfS', 69)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('CDjHlpSKNqRP@@sg]TT6sA]swmGsnwPbkmIpOI__aS', 'CDjHlpSKNqRP@@sg]TT6sA]swmGsnwPbkmIpOI__aSAsBEchHXzrQiFuCxbVqQVclCjTZtPzSgQW[xnhRILiOR]NeYC@ErFCKCT_gx]ukU]d@@BIxa]rbZiBQikIfSJvDQMkhgHIaenCCLiPuS[bkRAbeRb6AeHNSJUMS`TO', 70)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('AsBEchHXzrQiFuCxbVqQVclCjTZtPzSgQW[xnhRILi', 'AsBEchHXzrQiFuCxbVqQVclCjTZtPzSgQW[xnhRILiOR]NeYC@ErFCKCT_gx]ukU]d@@BIxa]rbZiBQikIfSJvDQMkhgHIaenCCLiPuS[bkRAbeRb6AeHNSJUMS`TOLTJsbWvOaxrzb6VAaVruNeeIltpSEfsDaikYumwZGB', 71)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('OR]NeYC@ErFCKCT_gx]ukU]d@@BIxa]rbZiBQikIfS', 'OR]NeYC@ErFCKCT_gx]ukU]d@@BIxa]rbZiBQikIfSJvDQMkhgHIaenCCLiPuS[bkRAbeRb6AeHNSJUMS`TOLTJsbWvOaxrzb6VAaVruNeeIltpSEfsDaikYumwZGBugnFLJbeEtC]wc[vxPZkifsCx_TcU[RTQgHy_EZkHQ', 72)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('JvDQMkhgHIaenCCLiPuS[bkRAbeRb6AeHNSJUMS`TO', 'JvDQMkhgHIaenCCLiPuS[bkRAbeRb6AeHNSJUMS`TOLTJsbWvOaxrzb6VAaVruNeeIltpSEfsDaikYumwZGBugnFLJbeEtC]wc[vxPZkifsCx_TcU[RTQgHy_EZkHQ]bThgc[6B6KnoxFvlU_H]aIDhmac[ia[IEYzWRmQ[e', 73)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('LTJsbWvOaxrzb6VAaVruNeeIltpSEfsDaikYumwZGB', 'LTJsbWvOaxrzb6VAaVruNeeIltpSEfsDaikYumwZGBugnFLJbeEtC]wc[vxPZkifsCx_TcU[RTQgHy_EZkHQ]bThgc[6B6KnoxFvlU_H]aIDhmac[ia[IEYzWRmQ[e6KNmOtRGkxEZBsucTWNmAqdIkephOd@KNeETobuslO', 74)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('ugnFLJbeEtC]wc[vxPZkifsCx_TcU[RTQgHy_EZkHQ', 'ugnFLJbeEtC]wc[vxPZkifsCx_TcU[RTQgHy_EZkHQ]bThgc[6B6KnoxFvlU_H]aIDhmac[ia[IEYzWRmQ[e6KNmOtRGkxEZBsucTWNmAqdIkephOd@KNeETobuslOkWF]SA[vsHIv]itBMN6nOdSuwUxWzQBPDLGNsjjDHr', 75)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES (']bThgc[6B6KnoxFvlU_H]aIDhmac[ia[IEYzWRmQ[e', ']bThgc[6B6KnoxFvlU_H]aIDhmac[ia[IEYzWRmQ[e6KNmOtRGkxEZBsucTWNmAqdIkephOd@KNeETobuslOkWF]SA[vsHIv]itBMN6nOdSuwUxWzQBPDLGNsjjDHrMM[UfIlIHYNhHiNgdjsTDBiKDweaRuZ]EyHf[TbTJF', 76)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('6KNmOtRGkxEZBsucTWNmAqdIkephOd@KNeETobuslO', '6KNmOtRGkxEZBsucTWNmAqdIkephOd@KNeETobuslOkWF]SA[vsHIv]itBMN6nOdSuwUxWzQBPDLGNsjjDHrMM[UfIlIHYNhHiNgdjsTDBiKDweaRuZ]EyHf[TbTJFnydihnbPNpsdKnbMXc]xgPcmNOxK_bXwsG`Z]YvtLB', 77)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('kWF]SA[vsHIv]itBMN6nOdSuwUxWzQBPDLGNsjjDHr', 'kWF]SA[vsHIv]itBMN6nOdSuwUxWzQBPDLGNsjjDHrMM[UfIlIHYNhHiNgdjsTDBiKDweaRuZ]EyHf[TbTJFnydihnbPNpsdKnbMXc]xgPcmNOxK_bXwsG`Z]YvtLB_JeeYSXUbGkkAeJfGSc_cHRMj[PuKXYhW]idr_lYlb', 78)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('MM[UfIlIHYNhHiNgdjsTDBiKDweaRuZ]EyHf[TbTJF', 'MM[UfIlIHYNhHiNgdjsTDBiKDweaRuZ]EyHf[TbTJFnydihnbPNpsdKnbMXc]xgPcmNOxK_bXwsG`Z]YvtLB_JeeYSXUbGkkAeJfGSc_cHRMj[PuKXYhW]idr_lYlbWZqtNwts_NU@UNA_J__BDjrOLI]LvMDBNZh[QzT`z', 79)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('nydihnbPNpsdKnbMXc]xgPcmNOxK_bXwsG`Z]YvtLB', 'nydihnbPNpsdKnbMXc]xgPcmNOxK_bXwsG`Z]YvtLB_JeeYSXUbGkkAeJfGSc_cHRMj[PuKXYhW]idr_lYlbWZqtNwts_NU@UNA_J__BDjrOLI]LvMDBNZh[QzT`zmrsbLigZOE[efYwKmzetluuvjDZcbmKOl`tIz_TWPmj', 80)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('_JeeYSXUbGkkAeJfGSc_cHRMj[PuKXYhW]idr_lYlb', '_JeeYSXUbGkkAeJfGSc_cHRMj[PuKXYhW]idr_lYlbWZqtNwts_NU@UNA_J__BDjrOLI]LvMDBNZh[QzT`zmrsbLigZOE[efYwKmzetluuvjDZcbmKOl`tIz_TWPmjjWsGLvCGa@kFHJ]PJCpO6fW_Llhmy]AkFAaO@OEODS', 81)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('WZqtNwts_NU@UNA_J__BDjrOLI]LvMDBNZh[QzT`z', 'WZqtNwts_NU@UNA_J__BDjrOLI]LvMDBNZh[QzT`zmrsbLigZOE[efYwKmzetluuvjDZcbmKOl`tIz_TWPmjjWsGLvCGa@kFHJ]PJCpO6fW_Llhmy]AkFAaO@OEODS[uPtIMIsPxdyRuUXdr6zYBiRAArM6FOskjevOjzuEh', 82)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('rsbLigZOE[efYwKmzetluuvjDZcbmKOl`tIz_TWPmj', 'rsbLigZOE[efYwKmzetluuvjDZcbmKOl`tIz_TWPmjjWsGLvCGa@kFHJ]PJCpO6fW_Llhmy]AkFAaO@OEODS[uPtIMIsPxdyRuUXdr6zYBiRAArM6FOskjevOjzuEhSxAPkKbAgtlqEm]MbxHIqod6eRKwbVJdr]odrrbm[r', 83)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('jWsGLvCGa@kFHJ]PJCpO6fW_Llhmy]AkFAaO@OEODS', 'jWsGLvCGa@kFHJ]PJCpO6fW_Llhmy]AkFAaO@OEODS[uPtIMIsPxdyRuUXdr6zYBiRAArM6FOskjevOjzuEhSxAPkKbAgtlqEm]MbxHIqod6eRKwbVJdr]odrrbm[rtpZysdAlUyangbRolFTWNA]]EzJoJTMTYP_BseCm_G', 84)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('[uPtIMIsPxdyRuUXdr6zYBiRAArM6FOskjevOjzuEh', '[uPtIMIsPxdyRuUXdr6zYBiRAArM6FOskjevOjzuEhSxAPkKbAgtlqEm]MbxHIqod6eRKwbVJdr]odrrbm[rtpZysdAlUyangbRolFTWNA]]EzJoJTMTYP_BseCm_GPep6up_EUl@Dca[KxOGStX[[@a@DM@qJOESfpUqhWG', 85)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('SxAPkKbAgtlqEm]MbxHIqod6eRKwbVJdr]odrrbm[r', 'SxAPkKbAgtlqEm]MbxHIqod6eRKwbVJdr]odrrbm[rtpZysdAlUyangbRolFTWNA]]EzJoJTMTYP_BseCm_GPep6up_EUl@Dca[KxOGStX[[@a@DM@qJOESfpUqhWGKCZSQvmSbtbNgfmcWVdWG]SGJAHRc]fXXomV@pXCSD', 86)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('tpZysdAlUyangbRolFTWNA]]EzJoJTMTYP_BseCm_G', 'tpZysdAlUyangbRolFTWNA]]EzJoJTMTYP_BseCm_GPep6up_EUl@Dca[KxOGStX[[@a@DM@qJOESfpUqhWGKCZSQvmSbtbNgfmcWVdWG]SGJAHRc]fXXomV@pXCSDpm_JrbamSSwO6jIAuUVPa@X[FBaTNObcgmGYEMojig', 87)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Pep6up_EUl@Dca[KxOGStX[[@a@DM@qJOESfpUqhWG', 'Pep6up_EUl@Dca[KxOGStX[[@a@DM@qJOESfpUqhWGKCZSQvmSbtbNgfmcWVdWG]SGJAHRc]fXXomV@pXCSDpm_JrbamSSwO6jIAuUVPa@X[FBaTNObcgmGYEMojigfzTbbXEaskACetKNFaxnK_LsEhQiUZJIVpQDdBFscF', 88)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('KCZSQvmSbtbNgfmcWVdWG]SGJAHRc]fXXomV@pXCSD', 'KCZSQvmSbtbNgfmcWVdWG]SGJAHRc]fXXomV@pXCSDpm_JrbamSSwO6jIAuUVPa@X[FBaTNObcgmGYEMojigfzTbbXEaskACetKNFaxnK_LsEhQiUZJIVpQDdBFscFcYGYuNMXaZNgEcjLUZAGeyShQ_OVnyrylIeEpxOXaJ', 89)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('pm_JrbamSSwO6jIAuUVPa@X[FBaTNObcgmGYEMojig', 'pm_JrbamSSwO6jIAuUVPa@X[FBaTNObcgmGYEMojigfzTbbXEaskACetKNFaxnK_LsEhQiUZJIVpQDdBFscFcYGYuNMXaZNgEcjLUZAGeyShQ_OVnyrylIeEpxOXaJlBJRkZDiRsB]gdi]FBZV@rVB@EHd@ekyeigUORZIQE', 90)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('fzTbbXEaskACetKNFaxnK_LsEhQiUZJIVpQDdBFscF', 'fzTbbXEaskACetKNFaxnK_LsEhQiUZJIVpQDdBFscFcYGYuNMXaZNgEcjLUZAGeyShQ_OVnyrylIeEpxOXaJlBJRkZDiRsB]gdi]FBZV@rVB@EHd@ekyeigUORZIQEVAkuntTDsHb6KL6QPAr]nmqlxmYVG[6[U_`LzNfan[', 91)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('cYGYuNMXaZNgEcjLUZAGeyShQ_OVnyrylIeEpxOXaJ', 'cYGYuNMXaZNgEcjLUZAGeyShQ_OVnyrylIeEpxOXaJlBJRkZDiRsB]gdi]FBZV@rVB@EHd@ekyeigUORZIQEVAkuntTDsHb6KL6QPAr]nmqlxmYVG[6[U_`LzNfan[fhKghTU@INDaOTbldubRgnlGFKnngb_eqmL[cpAERi', 92)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('lBJRkZDiRsB]gdi]FBZV@rVB@EHd@ekyeigUORZIQE', 'lBJRkZDiRsB]gdi]FBZV@rVB@EHd@ekyeigUORZIQEVAkuntTDsHb6KL6QPAr]nmqlxmYVG[6[U_`LzNfan[fhKghTU@INDaOTbldubRgnlGFKnngb_eqmL[cpAERiAbLXMXwVHVPFiSvGHj_KgE[EiomQ]fzzmmmEt`buP[', 93)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('VAkuntTDsHb6KL6QPAr]nmqlxmYVG[6[U_`LzNfan[', 'VAkuntTDsHb6KL6QPAr]nmqlxmYVG[6[U_`LzNfan[fhKghTU@INDaOTbldubRgnlGFKnngb_eqmL[cpAERiAbLXMXwVHVPFiSvGHj_KgE[EiomQ]fzzmmmEt`buP[bO_BbMEZnYln@CKoQMGxfYTDeIVCcabdmiehU@uibd', 94)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('fhKghTU@INDaOTbldubRgnlGFKnngb_eqmL[cpAERi', 'fhKghTU@INDaOTbldubRgnlGFKnngb_eqmL[cpAERiAbLXMXwVHVPFiSvGHj_KgE[EiomQ]fzzmmmEt`buP[bO_BbMEZnYln@CKoQMGxfYTDeIVCcabdmiehU@uibdmpViNuLGnEgwFwScowwwDlZccDgohERkZcbajmbUUs', 95)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('AbLXMXwVHVPFiSvGHj_KgE[EiomQ]fzzmmmEt`buP[', 'AbLXMXwVHVPFiSvGHj_KgE[EiomQ]fzzmmmEt`buP[bO_BbMEZnYln@CKoQMGxfYTDeIVCcabdmiehU@uibdmpViNuLGnEgwFwScowwwDlZccDgohERkZcbajmbUUsuNcnbRzCvFFJ_]zG6fnIVZVXzIUYqHGdGARfXkdpyO', 96)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('bO_BbMEZnYln@CKoQMGxfYTDeIVCcabdmiehU@uibd', 'bO_BbMEZnYln@CKoQMGxfYTDeIVCcabdmiehU@uibdmpViNuLGnEgwFwScowwwDlZccDgohERkZcbajmbUUsuNcnbRzCvFFJ_]zG6fnIVZVXzIUYqHGdGARfXkdpyOqFbGlpfSoVu_wgKLR@eBN[IBLH]tXtx`fLfjyAwbUa', 97)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('mpViNuLGnEgwFwScowwwDlZccDgohERkZcbajmbUUs', 'mpViNuLGnEgwFwScowwwDlZccDgohERkZcbajmbUUsuNcnbRzCvFFJ_]zG6fnIVZVXzIUYqHGdGARfXkdpyOqFbGlpfSoVu_wgKLR@eBN[IBLH]tXtx`fLfjyAwbUagOhwigagjMOoIxOVzhcKXstBY]xkcVukuO`bPmbmmQ', 98)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('uNcnbRzCvFFJ_]zG6fnIVZVXzIUYqHGdGARfXkdpyO', 'uNcnbRzCvFFJ_]zG6fnIVZVXzIUYqHGdGARfXkdpyOqFbGlpfSoVu_wgKLR@eBN[IBLH]tXtx`fLfjyAwbUagOhwigagjMOoIxOVzhcKXstBY]xkcVukuO`bPmbmmQNm_isYiX]uzYiYSvpBkie@bJ@[dgAOs[omfGBWtTLv', 99)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('qFbGlpfSoVu_wgKLR@eBN[IBLH]tXtx`fLfjyAwbUa', 'qFbGlpfSoVu_wgKLR@eBN[IBLH]tXtx`fLfjyAwbUagOhwigagjMOoIxOVzhcKXstBY]xkcVukuO`bPmbmmQNm_isYiX]uzYiYSvpBkie@bJ@[dgAOs[omfGBWtTLvzdbgGzjjjMaRdvPr[jsW[gMIPiDqQftRGFviADGy_K', 100)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('gOhwigagjMOoIxOVzhcKXstBY]xkcVukuO`bPmbmmQ', 'gOhwigagjMOoIxOVzhcKXstBY]xkcVukuO`bPmbmmQNm_isYiX]uzYiYSvpBkie@bJ@[dgAOs[omfGBWtTLvzdbgGzjjjMaRdvPr[jsW[gMIPiDqQftRGFviADGy_KubWEcqkmANxdKUwByKldCzzzowr[Nc6ltmqahuPAxn', 101)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Nm_isYiX]uzYiYSvpBkie@bJ@[dgAOs[omfGBWtTLv', 'Nm_isYiX]uzYiYSvpBkie@bJ@[dgAOs[omfGBWtTLvzdbgGzjjjMaRdvPr[jsW[gMIPiDqQftRGFviADGy_KubWEcqkmANxdKUwByKldCzzzowr[Nc6ltmqahuPAxn]sJ[nMJNtuMJhxpjB]vklVZVKLZrMLAmLFRqgZvaGo', 102)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('zdbgGzjjjMaRdvPr[jsW[gMIPiDqQftRGFviADGy_K', 'zdbgGzjjjMaRdvPr[jsW[gMIPiDqQftRGFviADGy_KubWEcqkmANxdKUwByKldCzzzowr[Nc6ltmqahuPAxn]sJ[nMJNtuMJhxpjB]vklVZVKLZrMLAmLFRqgZvaGoyIUjxMLJZSXR6bDbTdNaWXgGjHtENoVJtISHtXnqbW', 103)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('ubWEcqkmANxdKUwByKldCzzzowr[Nc6ltmqahuPAxn', 'ubWEcqkmANxdKUwByKldCzzzowr[Nc6ltmqahuPAxn]sJ[nMJNtuMJhxpjB]vklVZVKLZrMLAmLFRqgZvaGoyIUjxMLJZSXR6bDbTdNaWXgGjHtENoVJtISHtXnqbWuo[wPTgqFTZzfU6vBb6J_[uuwAPzZn[pNQxFvPgKhz', 104)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES (']sJ[nMJNtuMJhxpjB]vklVZVKLZrMLAmLFRqgZvaGo', ']sJ[nMJNtuMJhxpjB]vklVZVKLZrMLAmLFRqgZvaGoyIUjxMLJZSXR6bDbTdNaWXgGjHtENoVJtISHtXnqbWuo[wPTgqFTZzfU6vBb6J_[uuwAPzZn[pNQxFvPgKhznxAXRgQwbBSGtGcz__C_epUWUHMnojMr]XVEqFIVFe', 105)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('yIUjxMLJZSXR6bDbTdNaWXgGjHtENoVJtISHtXnqbW', 'yIUjxMLJZSXR6bDbTdNaWXgGjHtENoVJtISHtXnqbWuo[wPTgqFTZzfU6vBb6J_[uuwAPzZn[pNQxFvPgKhznxAXRgQwbBSGtGcz__C_epUWUHMnojMr]XVEqFIVFetxXvqIwRuzIXxnfhQFxMUomGlbeObBsT_RaDMbNMan', 106)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('uo[wPTgqFTZzfU6vBb6J_[uuwAPzZn[pNQxFvPgKhz', 'uo[wPTgqFTZzfU6vBb6J_[uuwAPzZn[pNQxFvPgKhznxAXRgQwbBSGtGcz__C_epUWUHMnojMr]XVEqFIVFetxXvqIwRuzIXxnfhQFxMUomGlbeObBsT_RaDMbNManvAz[b6RihFmJi_woplbYvNZEendg_UbXYrLookp_g@', 107)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('nxAXRgQwbBSGtGcz__C_epUWUHMnojMr]XVEqFIVFe', 'nxAXRgQwbBSGtGcz__C_epUWUHMnojMr]XVEqFIVFetxXvqIwRuzIXxnfhQFxMUomGlbeObBsT_RaDMbNManvAz[b6RihFmJi_woplbYvNZEendg_UbXYrLookp_g@qbcUbV]TXwxuIADZ_uWK_yd6ByhFUgySumOl[RWFuW', 108)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('txXvqIwRuzIXxnfhQFxMUomGlbeObBsT_RaDMbNMan', 'txXvqIwRuzIXxnfhQFxMUomGlbeObBsT_RaDMbNManvAz[b6RihFmJi_woplbYvNZEendg_UbXYrLookp_g@qbcUbV]TXwxuIADZ_uWK_yd6ByhFUgySumOl[RWFuWvv[Hr6gyOwk_obA[kYBWrYbLBuWYNijj_YZ]RzmFWS', 109)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('vAz[b6RihFmJi_woplbYvNZEendg_UbXYrLookp_g@', 'vAz[b6RihFmJi_woplbYvNZEendg_UbXYrLookp_g@qbcUbV]TXwxuIADZ_uWK_yd6ByhFUgySumOl[RWFuWvv[Hr6gyOwk_obA[kYBWrYbLBuWYNijj_YZ]RzmFWSsiVeZcxEaSz[dKwuKLzKUSXYL6xrCfkOSMA`vm]dGx', 110)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('qbcUbV]TXwxuIADZ_uWK_yd6ByhFUgySumOl[RWFuW', 'qbcUbV]TXwxuIADZ_uWK_yd6ByhFUgySumOl[RWFuWvv[Hr6gyOwk_obA[kYBWrYbLBuWYNijj_YZ]RzmFWSsiVeZcxEaSz[dKwuKLzKUSXYL6xrCfkOSMA`vm]dGxTY]ozHQmubdLBaAfwnY6nf_gKOw[AXGBLeLDSZGmrq', 111)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('vv[Hr6gyOwk_obA[kYBWrYbLBuWYNijj_YZ]RzmFWS', 'vv[Hr6gyOwk_obA[kYBWrYbLBuWYNijj_YZ]RzmFWSsiVeZcxEaSz[dKwuKLzKUSXYL6xrCfkOSMA`vm]dGxTY]ozHQmubdLBaAfwnY6nf_gKOw[AXGBLeLDSZGmrqWNJwduXFCtWjIyRMeReEFwjnpfQzd][dgXuuySIFRP', 112)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('siVeZcxEaSz[dKwuKLzKUSXYL6xrCfkOSMA`vm]dGx', 'siVeZcxEaSz[dKwuKLzKUSXYL6xrCfkOSMA`vm]dGxTY]ozHQmubdLBaAfwnY6nf_gKOw[AXGBLeLDSZGmrqWNJwduXFCtWjIyRMeReEFwjnpfQzd][dgXuuySIFRPGp6XEtRvGH[ixqVhQig6vFiVEAvjPnezCmDNQlbTsM', 113)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('TY]ozHQmubdLBaAfwnY6nf_gKOw[AXGBLeLDSZGmrq', 'TY]ozHQmubdLBaAfwnY6nf_gKOw[AXGBLeLDSZGmrqWNJwduXFCtWjIyRMeReEFwjnpfQzd][dgXuuySIFRPGp6XEtRvGH[ixqVhQig6vFiVEAvjPnezCmDNQlbTsMMAqkwaIFvtijnY6bz@XCaZDfxR6McNsnwTyb`bcNZa', 114)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('WNJwduXFCtWjIyRMeReEFwjnpfQzd][dgXuuySIFRP', 'WNJwduXFCtWjIyRMeReEFwjnpfQzd][dgXuuySIFRPGp6XEtRvGH[ixqVhQig6vFiVEAvjPnezCmDNQlbTsMMAqkwaIFvtijnY6bz@XCaZDfxR6McNsnwTyb`bcNZaSANbz[hGN@FyRVWfM]KOuX[TPxH@]bVcl`bkyoSflC', 115)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Gp6XEtRvGH[ixqVhQig6vFiVEAvjPnezCmDNQlbTsM', 'Gp6XEtRvGH[ixqVhQig6vFiVEAvjPnezCmDNQlbTsMMAqkwaIFvtijnY6bz@XCaZDfxR6McNsnwTyb`bcNZaSANbz[hGN@FyRVWfM]KOuX[TPxH@]bVcl`bkyoSflCKbfVm@FzOufEYnb@kVJh@ekIFQIirPeQzDGaM]BOQF', 116)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('MAqkwaIFvtijnY6bz@XCaZDfxR6McNsnwTyb`bcNZa', 'MAqkwaIFvtijnY6bz@XCaZDfxR6McNsnwTyb`bcNZaSANbz[hGN@FyRVWfM]KOuX[TPxH@]bVcl`bkyoSflCKbfVm@FzOufEYnb@kVJh@ekIFQIirPeQzDGaM]BOQFdlk@lBplkcCQYHyRQtnILYgRSeOJiCbjTFvN]zjNEW', 117)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('SANbz[hGN@FyRVWfM]KOuX[TPxH@]bVcl`bkyoSflC', 'SANbz[hGN@FyRVWfM]KOuX[TPxH@]bVcl`bkyoSflCKbfVm@FzOufEYnb@kVJh@ekIFQIirPeQzDGaM]BOQFdlk@lBplkcCQYHyRQtnILYgRSeOJiCbjTFvN]zjNEWhx6kSgpubgYrAzTOggkfjaViFWJPKULAnCRaKqaFbc', 118)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('KbfVm@FzOufEYnb@kVJh@ekIFQIirPeQzDGaM]BOQF', 'KbfVm@FzOufEYnb@kVJh@ekIFQIirPeQzDGaM]BOQFdlk@lBplkcCQYHyRQtnILYgRSeOJiCbjTFvN]zjNEWhx6kSgpubgYrAzTOggkfjaViFWJPKULAnCRaKqaFbcNpTcgbPpILsb@OEbbHgGvdCfnSaxv]mmrmWfAmbTYa', 119)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('dlk@lBplkcCQYHyRQtnILYgRSeOJiCbjTFvN]zjNEW', 'dlk@lBplkcCQYHyRQtnILYgRSeOJiCbjTFvN]zjNEWhx6kSgpubgYrAzTOggkfjaViFWJPKULAnCRaKqaFbcNpTcgbPpILsb@OEbbHgGvdCfnSaxv]mmrmWfAmbTYawZxIzYWwXUYNV_txjKkolIvcYoYELkgUniF_qDbGzc', 120)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('hx6kSgpubgYrAzTOggkfjaViFWJPKULAnCRaKqaFbc', 'hx6kSgpubgYrAzTOggkfjaViFWJPKULAnCRaKqaFbcNpTcgbPpILsb@OEbbHgGvdCfnSaxv]mmrmWfAmbTYawZxIzYWwXUYNV_txjKkolIvcYoYELkgUniF_qDbGzcrAegouI[GhlgO6aCZq_XP[w]J_qnaAshiGXpqo]baO', 121)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('NpTcgbPpILsb@OEbbHgGvdCfnSaxv]mmrmWfAmbTYa', 'NpTcgbPpILsb@OEbbHgGvdCfnSaxv]mmrmWfAmbTYawZxIzYWwXUYNV_txjKkolIvcYoYELkgUniF_qDbGzcrAegouI[GhlgO6aCZq_XP[w]J_qnaAshiGXpqo]baOHsOKSwRQK[MvmsRPbgQdixUQiRtZMoeNF[XvGEaBsX', 122)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('wZxIzYWwXUYNV_txjKkolIvcYoYELkgUniF_qDbGzc', 'wZxIzYWwXUYNV_txjKkolIvcYoYELkgUniF_qDbGzcrAegouI[GhlgO6aCZq_XP[w]J_qnaAshiGXpqo]baOHsOKSwRQK[MvmsRPbgQdixUQiRtZMoeNF[XvGEaBsXRjPvUGSLAYxgHPESRketYmbmaToYpgN@nawEpQDACJ', 123)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('rAegouI[GhlgO6aCZq_XP[w]J_qnaAshiGXpqo]baO', 'rAegouI[GhlgO6aCZq_XP[w]J_qnaAshiGXpqo]baOHsOKSwRQK[MvmsRPbgQdixUQiRtZMoeNF[XvGEaBsXRjPvUGSLAYxgHPESRketYmbmaToYpgN@nawEpQDACJhb@Di6jf]bWl@jyOm6pZGQyIoQdfgilSmwScgCADsg', 124)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('HsOKSwRQK[MvmsRPbgQdixUQiRtZMoeNF[XvGEaBsX', 'HsOKSwRQK[MvmsRPbgQdixUQiRtZMoeNF[XvGEaBsXRjPvUGSLAYxgHPESRketYmbmaToYpgN@nawEpQDACJhb@Di6jf]bWl@jyOm6pZGQyIoQdfgilSmwScgCADsgTcbq@MT_qOYgiTTQZkomQnoHW_DoyVSnu`XWo]NiD_', 125)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('RjPvUGSLAYxgHPESRketYmbmaToYpgN@nawEpQDACJ', 'RjPvUGSLAYxgHPESRketYmbmaToYpgN@nawEpQDACJhb@Di6jf]bWl@jyOm6pZGQyIoQdfgilSmwScgCADsgTcbq@MT_qOYgiTTQZkomQnoHW_DoyVSnu`XWo]NiD_uyRw@bOSANR_gsYVeKjuNXEOUoFwTEuxkONF`fyhSC', 126)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('hb@Di6jf]bWl@jyOm6pZGQyIoQdfgilSmwScgCADsg', 'hb@Di6jf]bWl@jyOm6pZGQyIoQdfgilSmwScgCADsgTcbq@MT_qOYgiTTQZkomQnoHW_DoyVSnu`XWo]NiD_uyRw@bOSANR_gsYVeKjuNXEOUoFwTEuxkONF`fyhSCYnYViVhm_UoG[hjoeqDqSJMeYU@rCvwOjJEVCItdfW', 127)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Tcbq@MT_qOYgiTTQZkomQnoHW_DoyVSnu`XWo]NiD_', 'Tcbq@MT_qOYgiTTQZkomQnoHW_DoyVSnu`XWo]NiD_uyRw@bOSANR_gsYVeKjuNXEOUoFwTEuxkONF`fyhSCYnYViVhm_UoG[hjoeqDqSJMeYU@rCvwOjJEVCItdfWkO_xlUdAYJlBtnKUjwgdH]Fanjns[hlfBylFiDPeTQ', 128)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('uyRw@bOSANR_gsYVeKjuNXEOUoFwTEuxkONF`fyhSC', 'uyRw@bOSANR_gsYVeKjuNXEOUoFwTEuxkONF`fyhSCYnYViVhm_UoG[hjoeqDqSJMeYU@rCvwOjJEVCItdfWkO_xlUdAYJlBtnKUjwgdH]Fanjns[hlfBylFiDPeTQXhkXmEasqaVgQviMQV@McyDiTLdoGXDELqzQVbu`M', 129)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('YnYViVhm_UoG[hjoeqDqSJMeYU@rCvwOjJEVCItdfW', 'YnYViVhm_UoG[hjoeqDqSJMeYU@rCvwOjJEVCItdfWkO_xlUdAYJlBtnKUjwgdH]Fanjns[hlfBylFiDPeTQXhkXmEasqaVgQviMQV@McyDiTLdoGXDELqzQVbu`MmXAHmBS[ySkLKqFYVDFxbO@EeoyUNCgXpIQtwrYVtbh', 130)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('kO_xlUdAYJlBtnKUjwgdH]Fanjns[hlfBylFiDPeTQ', 'kO_xlUdAYJlBtnKUjwgdH]Fanjns[hlfBylFiDPeTQXhkXmEasqaVgQviMQV@McyDiTLdoGXDELqzQVbu`MmXAHmBS[ySkLKqFYVDFxbO@EeoyUNCgXpIQtwrYVtbhFNnhgeggzIVB@_YUJypwqBgGeCeIryyZOZXCmZDRvd', 131)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('XhkXmEasqaVgQviMQV@McyDiTLdoGXDELqzQVbu`M', 'XhkXmEasqaVgQviMQV@McyDiTLdoGXDELqzQVbu`MmXAHmBS[ySkLKqFYVDFxbO@EeoyUNCgXpIQtwrYVtbhFNnhgeggzIVB@_YUJypwqBgGeCeIryyZOZXCmZDRvdvrAoKgUNnkF@fEuseQxuOIETiwUYr6gVhQ@tWHXtbi', 132)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('XAHmBS[ySkLKqFYVDFxbO@EeoyUNCgXpIQtwrYVtbh', 'XAHmBS[ySkLKqFYVDFxbO@EeoyUNCgXpIQtwrYVtbhFNnhgeggzIVB@_YUJypwqBgGeCeIryyZOZXCmZDRvdvrAoKgUNnkF@fEuseQxuOIETiwUYr6gVhQ@tWHXtbiYSZmjFBbw[[gilbCaMg6nguEfM6GVewYcEIFKXNomP', 133)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('FNnhgeggzIVB@_YUJypwqBgGeCeIryyZOZXCmZDRvd', 'FNnhgeggzIVB@_YUJypwqBgGeCeIryyZOZXCmZDRvdvrAoKgUNnkF@fEuseQxuOIETiwUYr6gVhQ@tWHXtbiYSZmjFBbw[[gilbCaMg6nguEfM6GVewYcEIFKXNomPY_eoMWAJz_VfMcBPfkOr]cLKSEnUiMpcDCYxbb`Dh@', 134)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('vrAoKgUNnkF@fEuseQxuOIETiwUYr6gVhQ@tWHXtbi', 'vrAoKgUNnkF@fEuseQxuOIETiwUYr6gVhQ@tWHXtbiYSZmjFBbw[[gilbCaMg6nguEfM6GVewYcEIFKXNomPY_eoMWAJz_VfMcBPfkOr]cLKSEnUiMpcDCYxbb`Dh@pkpgsfFbFwZZ[ByWZSAnJfbBhUQ6VWAqdCIxTIEZId', 135)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('YSZmjFBbw[[gilbCaMg6nguEfM6GVewYcEIFKXNomP', 'YSZmjFBbw[[gilbCaMg6nguEfM6GVewYcEIFKXNomPY_eoMWAJz_VfMcBPfkOr]cLKSEnUiMpcDCYxbb`Dh@pkpgsfFbFwZZ[ByWZSAnJfbBhUQ6VWAqdCIxTIEZIdrs_]vQdr6nHxRs@P[moq_EmbfXwmycPgVPHRnZOySd', 136)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('Y_eoMWAJz_VfMcBPfkOr]cLKSEnUiMpcDCYxbb`Dh@', 'Y_eoMWAJz_VfMcBPfkOr]cLKSEnUiMpcDCYxbb`Dh@pkpgsfFbFwZZ[ByWZSAnJfbBhUQ6VWAqdCIxTIEZIdrs_]vQdr6nHxRs@P[moq_EmbfXwmycPgVPHRnZOySdmS@ldrcKLMAmWsB_H@WBj[GaDbJgWm[ZNI@vtkldjY', 137)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('pkpgsfFbFwZZ[ByWZSAnJfbBhUQ6VWAqdCIxTIEZId', 'pkpgsfFbFwZZ[ByWZSAnJfbBhUQ6VWAqdCIxTIEZIdrs_]vQdr6nHxRs@P[moq_EmbfXwmycPgVPHRnZOySdmS@ldrcKLMAmWsB_H@WBj[GaDbJgWm[ZNI@vtkldjYR@JXEAWZJDyAxgzcMFuqHWqMiqQHxlMphaSFX@OzFM', 138)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('rs_]vQdr6nHxRs@P[moq_EmbfXwmycPgVPHRnZOySd', 'rs_]vQdr6nHxRs@P[moq_EmbfXwmycPgVPHRnZOySdmS@ldrcKLMAmWsB_H@WBj[GaDbJgWm[ZNI@vtkldjYR@JXEAWZJDyAxgzcMFuqHWqMiqQHxlMphaSFX@OzFMe[hguRzEGCbcLSBbmRUuUWKHzI_D]TQBvbHUhOihbh', 139)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('mS@ldrcKLMAmWsB_H@WBj[GaDbJgWm[ZNI@vtkldjY', 'mS@ldrcKLMAmWsB_H@WBj[GaDbJgWm[ZNI@vtkldjYR@JXEAWZJDyAxgzcMFuqHWqMiqQHxlMphaSFX@OzFMe[hguRzEGCbcLSBbmRUuUWKHzI_D]TQBvbHUhOihbhob@JQ6bseSVxrcMZFP]EMSvcQNpoaNg]IvIvWmIhqa', 140)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('R@JXEAWZJDyAxgzcMFuqHWqMiqQHxlMphaSFX@OzFM', 'R@JXEAWZJDyAxgzcMFuqHWqMiqQHxlMphaSFX@OzFMe[hguRzEGCbcLSBbmRUuUWKHzI_D]TQBvbHUhOihbhob@JQ6bseSVxrcMZFP]EMSvcQNpoaNg]IvIvWmIhqaUpxgPopxjcZvSmaU[vdBNqeXXJPsa[oNHfZfmvevEW', 141)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('e[hguRzEGCbcLSBbmRUuUWKHzI_D]TQBvbHUhOihbh', 'e[hguRzEGCbcLSBbmRUuUWKHzI_D]TQBvbHUhOihbhob@JQ6bseSVxrcMZFP]EMSvcQNpoaNg]IvIvWmIhqaUpxgPopxjcZvSmaU[vdBNqeXXJPsa[oNHfZfmvevEWOZwN[jmBUbygRGQYPbXtA_SHXmgpHzT]mq_ynJLVzN', 142)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('ob@JQ6bseSVxrcMZFP]EMSvcQNpoaNg]IvIvWmIhqa', 'ob@JQ6bseSVxrcMZFP]EMSvcQNpoaNg]IvIvWmIhqaUpxgPopxjcZvSmaU[vdBNqeXXJPsa[oNHfZfmvevEWOZwN[jmBUbygRGQYPbXtA_SHXmgpHzT]mq_ynJLVzNPMZj6kMeZMYSmLbAsUNO_bHzkv@_yCjCsEnGDAO[_c', 143)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('UpxgPopxjcZvSmaU[vdBNqeXXJPsa[oNHfZfmvevEW', 'UpxgPopxjcZvSmaU[vdBNqeXXJPsa[oNHfZfmvevEWOZwN[jmBUbygRGQYPbXtA_SHXmgpHzT]mq_ynJLVzNPMZj6kMeZMYSmLbAsUNO_bHzkv@_yCjCsEnGDAO[_cJenLDnA[ihkezjWDUOgbhGKPvKUBNYI[YpCsqIenE`', 144)");
            migrationBuilder.Sql("INSERT INTO Artigos (Chamada, Corpo, FonteId) VALUES ('OZwN[jmBUbygRGQYPbXtA_SHXmgpHzT]mq_ynJLVzN', 'OZwN[jmBUbygRGQYPbXtA_SHXmgpHzT]mq_ynJLVzNPMZj6kMeZMYSmLbAsUNO_bHzkv@_yCjCsEnGDAO[_cJenLDnA[ihkezjWDUOgbhGKPvKUBNYI[YpCsqIenE`tnfuZCMGAjgeVXzEqfDazhsghsiwaRCwaJmvaacS@J', 145)");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 52)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 53)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 54)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 55)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 56)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 57)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 58)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 59)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 60)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 61)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 62)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 63)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 64)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 65)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 66)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 67)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 68)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 69)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 70)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 71)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 72)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 73)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 74)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 75)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 76)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 77)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 78)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 79)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 80)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 81)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 82)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 83)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 84)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 85)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 86)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 87)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 88)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 89)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 90)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 91)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 92)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 93)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 94)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 95)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 96)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 97)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 98)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 99)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 100)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 101)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 102)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 103)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 104)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 105)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 106)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 107)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 108)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 109)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 110)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 111)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 112)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 113)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 114)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 115)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 116)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 117)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 118)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 119)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 120)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 121)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 122)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 123)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 124)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 125)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 126)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 127)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 128)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 129)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 130)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 131)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 132)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 133)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 134)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 135)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 136)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 137)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 138)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 139)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 140)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 141)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 142)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 143)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 144)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 145)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 146)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 147)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 148)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 149)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 150)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 151)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 152)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 153)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 154)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 155)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 156)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 157)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 158)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 159)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 160)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 161)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 162)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 163)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 164)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 165)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 166)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 167)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 168)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 169)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 170)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 171)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 172)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 173)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 174)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 175)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 176)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 177)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 178)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 179)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 180)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 181)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 182)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 183)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 184)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 185)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 186)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 187)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 188)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 189)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 190)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 191)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 192)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 193)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 194)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 195)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 196)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 197)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 198)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 199)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 200)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 201)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 202)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 203)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 204)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 205)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 206)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 207)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 208)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 209)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 210)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 211)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 212)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 213)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 214)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 215)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 216)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 217)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 218)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 219)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 220)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 221)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 222)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 223)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 224)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 225)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 226)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 227)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 228)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 229)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 230)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 231)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 232)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 233)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 234)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 235)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 236)");
            migrationBuilder.Sql("DELETE FROM Artigos WHERE FonteId = 237)");
        }
    }
}
