using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KnowledgeBase.Migrations
{
    public partial class PopulateErrorInFull : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 103', 'Código: 337', 90)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 104', 'Código: 133', 91)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 105', 'Código: 745', 92)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 106', 'Código: 690', 93)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 107', 'Código: 288', 94)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 108', 'Código: 656', 95)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 109', 'Código: 32', 96)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 110', 'Código: 715', 97)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 111', 'Código: 485', 98)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 112', 'Código: 838', 99)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 113', 'Código: 320', 100)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 114', 'Código: 695', 101)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 115', 'Código: 877', 102)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 116', 'Código: 171', 103)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 117', 'Código: 384', 104)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 118', 'Código: 506', 105)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 119', 'Código: 863', 106)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 120', 'Código: 897', 107)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 121', 'Código: 371', 108)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 122', 'Código: 597', 109)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 123', 'Código: 0', 110)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 124', 'Código: 728', 111)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 125', 'Código: 232', 112)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 126', 'Código: 563', 113)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 127', 'Código: 46', 114)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 128', 'Código: 795', 115)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 129', 'Código: 272', 116)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 130', 'Código: 492', 117)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 131', 'Código: 340', 118)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 132', 'Código: 333', 119)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 133', 'Código: 828', 120)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 134', 'Código: 663', 121)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 135', 'Código: 209', 122)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 136', 'Código: 577', 123)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 137', 'Código: 289', 124)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 138', 'Código: 44', 125)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 139', 'Código: 159', 126)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 140', 'Código: 676', 127)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 141', 'Código: 103', 128)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 142', 'Código: 179', 129)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 143', 'Código: 292', 130)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 144', 'Código: 466', 131)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 145', 'Código: 788', 132)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 146', 'Código: 746', 133)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 147', 'Código: 632', 134)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 148', 'Código: 183', 135)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 149', 'Código: 465', 136)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 150', 'Código: 407', 137)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 151', 'Código: 47', 138)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 152', 'Código: 35', 139)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 153', 'Código: 724', 140)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 154', 'Código: 342', 141)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 155', 'Código: 429', 142)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 156', 'Código: 317', 143)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 157', 'Código: 846', 144)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 158', 'Código: 278', 145)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 159', 'Código: 232', 146)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 160', 'Código: 994', 147)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 161', 'Código: 972', 148)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 162', 'Código: 545', 149)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 163', 'Código: 163', 150)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 164', 'Código: 588', 151)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 165', 'Código: 609', 152)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 166', 'Código: 322', 153)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 167', 'Código: 837', 154)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 168', 'Código: 297', 155)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 169', 'Código: 196', 156)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 170', 'Código: 125', 157)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 171', 'Código: 871', 158)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 172', 'Código: 530', 159)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 173', 'Código: 95', 160)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 174', 'Código: 686', 161)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 175', 'Código: 838', 162)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 176', 'Código: 61', 163)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 177', 'Código: 229', 164)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 178', 'Código: 899', 165)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 179', 'Código: 668', 166)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 180', 'Código: 56', 167)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 181', 'Código: 227', 168)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 182', 'Código: 124', 169)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 183', 'Código: 189', 170)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 184', 'Código: 807', 171)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 185', 'Código: 120', 172)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 186', 'Código: 191', 173)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 187', 'Código: 429', 174)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 188', 'Código: 684', 175)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 189', 'Código: 416', 176)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 190', 'Código: 353', 177)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 191', 'Código: 60', 178)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 192', 'Código: 285', 179)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 193', 'Código: 824', 180)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 194', 'Código: 627', 181)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 195', 'Código: 649', 182)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 196', 'Código: 316', 183)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 197', 'Código: 452', 184)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 198', 'Código: 579', 185)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 199', 'Código: 848', 186)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 200', 'Código: 306', 187)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 201', 'Código: 209', 188)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 202', 'Código: 366', 189)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 203', 'Código: 875', 190)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 204', 'Código: 229', 191)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 205', 'Código: 913', 192)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 206', 'Código: 617', 193)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 207', 'Código: 169', 194)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 208', 'Código: 84', 195)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 209', 'Código: 820', 196)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 210', 'Código: 381', 197)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 211', 'Código: 257', 198)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 212', 'Código: 15', 199)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 213', 'Código: 980', 200)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 214', 'Código: 563', 201)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 215', 'Código: 370', 202)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 216', 'Código: 917', 203)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 217', 'Código: 851', 204)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 218', 'Código: 357', 205)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 219', 'Código: 83', 206)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 220', 'Código: 624', 207)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 221', 'Código: 571', 208)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 222', 'Código: 282', 209)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 223', 'Código: 867', 210)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 224', 'Código: 812', 211)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 225', 'Código: 499', 212)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 226', 'Código: 534', 213)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 227', 'Código: 339', 214)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 228', 'Código: 175', 215)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 229', 'Código: 777', 216)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 230', 'Código: 338', 217)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 231', 'Código: 215', 218)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 232', 'Código: 757', 219)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 233', 'Código: 793', 220)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 234', 'Código: 380', 221)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 235', 'Código: 844', 222)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 236', 'Código: 98', 223)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 237', 'Código: 71', 224)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 238', 'Código: 312', 225)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 239', 'Código: 726', 226)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 240', 'Código: 201', 227)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 241', 'Código: 917', 228)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 242', 'Código: 85', 229)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 243', 'Código: 621', 230)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 244', 'Código: 837', 231)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 245', 'Código: 459', 232)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 246', 'Código: 513', 233)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 247', 'Código: 121', 234)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 248', 'Código: 309', 235)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 249', 'Código: 796', 236)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 250', 'Código: 145', 237)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 251', 'Código: 569', 238)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 252', 'Código: 658', 239)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 253', 'Código: 774', 240)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 254', 'Código: 247', 241)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 255', 'Código: 962', 242)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 256', 'Código: 682', 243)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 257', 'Código: 850', 244)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 258', 'Código: 765', 245)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 259', 'Código: 667', 246)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 260', 'Código: 208', 247)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 261', 'Código: 578', 248)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 262', 'Código: 682', 249)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 263', 'Código: 46', 250)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 264', 'Código: 32', 251)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 265', 'Código: 267', 252)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 266', 'Código: 357', 253)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 267', 'Código: 594', 254)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 268', 'Código: 457', 255)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 269', 'Código: 40', 256)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 270', 'Código: 598', 257)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 271', 'Código: 492', 258)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 272', 'Código: 292', 259)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 273', 'Código: 361', 260)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 274', 'Código: 190', 261)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 275', 'Código: 143', 262)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 276', 'Código: 954', 263)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 277', 'Código: 601', 264)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 278', 'Código: 213', 265)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 279', 'Código: 74', 266)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 280', 'Código: 262', 267)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 281', 'Código: 624', 268)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 282', 'Código: 821', 269)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 283', 'Código: 513', 270)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 284', 'Código: 609', 271)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 285', 'Código: 561', 272)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 286', 'Código: 769', 273)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 287', 'Código: 520', 274)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 288', 'Código: 685', 275)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 289', 'Código: 67', 276)");
            migrationBuilder.Sql("INSERT INTO Erros (Nome, Codigo, FrameworkId) VALUES ('Erro: 290', 'Código: 928', 277)");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  90)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  91)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  92)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  93)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  94)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  95)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  96)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  97)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  98)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  99)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  100)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  101)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  102)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  103)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  104)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  105)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  106)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  107)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  108)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  109)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  110)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  111)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  112)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  113)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  114)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  115)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  116)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  117)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  118)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  119)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  120)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  121)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  122)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  123)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  124)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  125)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  126)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  127)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  128)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  129)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  130)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  131)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  132)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  133)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  134)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  135)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  136)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  137)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  138)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  139)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  140)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  141)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  142)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  143)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  144)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  145)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  146)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  147)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  148)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  149)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  150)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  151)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  152)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  153)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  154)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  155)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  156)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  157)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  158)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  159)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  160)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  161)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  162)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  163)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  164)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  165)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  166)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  167)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  168)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  169)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  170)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  171)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  172)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  173)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  174)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  175)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  176)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  177)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  178)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  179)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  180)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  181)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  182)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  183)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  184)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  185)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  186)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  187)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  188)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  189)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  190)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  191)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  192)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  193)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  194)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  195)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  196)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  197)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  198)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  199)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  200)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  201)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  202)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  203)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  204)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  205)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  206)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  207)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  208)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  209)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  210)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  211)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  212)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  213)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  214)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  215)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  216)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  217)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  218)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  219)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  220)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  221)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  222)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  223)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  224)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  225)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  226)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  227)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  228)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  229)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  230)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  231)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  232)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  233)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  234)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  235)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  236)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  237)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  238)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  239)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  240)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  241)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  242)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  243)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  244)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  245)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  246)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  247)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  248)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  249)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  250)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  251)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  252)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  253)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  254)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  255)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  256)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  257)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  258)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  259)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  260)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  261)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  262)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  263)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  264)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  265)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  266)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  267)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  268)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  269)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  270)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  271)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  272)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  273)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  274)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  275)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  276)");
            migrationBuilder.Sql("DELETE FROM Erros WHERE FrameworkId =  277)");
        }
    }
}
